# Generated by Django 4.2 on 2025-04-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nb_cages', models.IntegerField()),
                ('qt_nourriture', models.IntegerField()),
                ('argent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('etat', models.CharField(max_length=10)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individus', to='elevage.elevage')),
            ],
        ),
    ]
