# Generated by Django 4.2 on 2025-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevage',
            name='argent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='nb_cages',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='qt_nourriture',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='individu',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='individu',
            name='etat',
            field=models.CharField(choices=[('présent', 'Présent'), ('vendu', 'Vendu'), ('mort', 'Mort'), ('gravide', 'Gravide')], max_length=10),
        ),
        migrations.AlterField(
            model_name='individu',
            name='sexe',
            field=models.CharField(choices=[('m', 'Mâle'), ('f', 'Femelle')], max_length=1),
        ),
    ]
