# Generated by Django 4.2 on 2025-04-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0002_alter_elevage_argent_alter_elevage_nb_cages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_sante', models.IntegerField(default=100)),
                ('maladies', models.TextField(blank=True, null=True)),
                ('dernier_checkup', models.DateField(auto_now=True)),
                ('individu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='elevage.individu')),
            ],
        ),
    ]
