# Generated by Django 4.2 on 2025-04-28 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elevage', '0002_alter_elevage_argent_alter_elevage_nb_cages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
