# Generated by Django 4.2 on 2025-04-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0002_alter_elevage_argent_alter_elevage_nb_cages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='tour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ElevageDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.IntegerField()),
                ('nb_males', models.IntegerField()),
                ('nb_femelles', models.IntegerField()),
                ('nb_lapereaux', models.IntegerField()),
                ('naissances', models.IntegerField()),
                ('morts', models.IntegerField()),
                ('ventes', models.IntegerField()),
                ('argent', models.IntegerField()),
                ('nourriture', models.IntegerField()),
                ('cages', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevage.elevage')),
            ],
        ),
    ]
