# Generated by Django 4.2 on 2025-04-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0003_elevage_tour_elevagedatas'),
        ('elevage', '0003_elevage_user'),
    ]

    operations = [
    ]
