# Generated by Django 4.2 on 2025-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0003_sante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sante',
            name='dernier_checkup',
        ),
        migrations.RemoveField(
            model_name='sante',
            name='maladies',
        ),
        migrations.AddField(
            model_name='sante',
            name='malade',
            field=models.BooleanField(default=False),
        ),
    ]
