# Generated by Django 4.2 on 2025-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0004_remove_sante_dernier_checkup_remove_sante_maladies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sante',
            name='individu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='elevage.individu'),
        ),
    ]
