# Generated by Django 4.2 on 2025-05-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0004_merge_20250428_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividuSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('m', 'Mâle'), ('f', 'Femelle')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('etat', models.CharField(choices=[('présent', 'Présent'), ('vendu', 'Vendu'), ('mort', 'Mort'), ('gravide', 'Gravide')], max_length=10)),
                ('elevage_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individus_snapshots', to='elevage.elevagedatas')),
            ],
        ),
    ]
