# Generated by Django 4.2 on 2025-04-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0005_alter_sante_individu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sante',
            name='individu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='elevage.individu'),
        ),
    ]
