# Generated by Django 4.2 on 2025-04-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0004_merge_20250428_1314'),
        ('elevage', '0006_alter_sante_individu'),
    ]

    operations = [
    ]
