# Generated by Django 4.2 on 2025-05-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0005_individusnapshot'),
        ('elevage', '0008_elevagedatas_malades'),
    ]

    operations = [
    ]
