# Generated by Django 4.2 on 2025-05-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevage', '0009_merge_0005_individusnapshot_0008_elevagedatas_malades'),
    ]

    operations = [
        migrations.AddField(
            model_name='individusnapshot',
            name='malade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individusnapshot',
            name='niveau_sante',
            field=models.IntegerField(default=100),
        ),
    ]
